model_list:
  - model_name: "gpt-4o"
    litellm_params:
      model: "openai/nvidia/nemotron-3-super-120b-a12b"
      api_base: "https://integrate.api.nvidia.com/v1"
      api_key: "os.environ/NVIDIA_NIM_API_KEY"
      rpm: 60

  - model_name: "text-embedding-3-large"
    litellm_params:
      model: "nvidia_nim/nvidia/nv-embed-v1"
      api_base: "http://127.0.0.1:8000/nvidia-intercept/v1"
      api_key: "os.environ/NVIDIA_NIM_API_KEY"
      rpm: 60
      drop_params: true

litellm_settings:
  drop_params: true
